import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import Background from "./components/background";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="./images/favicon.png"
          type="image/x-icon"
        />
      </head>
      <body
        className={`${inter.className} flex flex-col min-h-screen bg-slate-300 dark:bg-inherit antialiased overflow-hidden`}
      >
        <NavBar />
        <main className="relative flex-1 shadow-lg">
          {children}
          <Background />
        </main>
      </body>
    </html>
  );
}
